REPORT_COLUMNS = {
    "inventory_number": "No. inventario",
    "catalog_number": "No. catalogo",
    "origin_number": "No. procedencia",
    "description_origin": "Descripcion de origen",
    "description_inventory": "Descripcion de inventario",
    "gender.title": "Genero",
    "subgender.title": "Subgenero",
    "type_object.title": "Tipo de objeto",
    "dominant_material.title": "Material dominante",
    "tags": "Mueble",
    "appraisal": "Avaluo",
    "location.name": "Ubicacion",
    "measure_without": "Medidas sin base/marco",
    "measure_with": "Medidas con base/marco",
    "photo_inventory": "Foto de inventario",
    "piece.set.title": "Conjunto",
    "research.title": "Titulo",
    "research.authors": "Autor(es)",
    "research.involved_creation_ids": "Involucrados en su creacion",
    "research.technique": "Tecnica",
    "research.materials": "Materiales",
    "research.place_of_creation.title": "Procedencia",
    "research.creation_date": "Fecha de creacion",
    "research.period.title": "Epoca",
    "research.acquisition_form": "Proveniencia - Forma",
    "research.acquisition_source": "Proveniencia - Fuente/lugar",
    "research.acquisition_date": "Proveniencia - Fecha",
    "research.firm_description": "Firmas o marcas - Descripcion",
    "research.short_description": "Descripcion abreviada",
    "research.formal_description": "Descripcion formal",
    "research.observation": "Observaciones",
    "research.publications": "Publicaciones en las que aparece la obra",
    "photo_research": "Foto de investigacion",
    "research.card": "Cedula",
}
