"""
Django settings for MnemosineV3_0 project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/"""

import os

# Configuración de autenticación para JWT
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ivj7la__uiylc$a6b_usp#o^wqi#z19lr7tf3*z4y7ns39kui-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "la-ea.duckdns.org",
    "192.168.1.70",
    
    "and-pad.duckdns.org",
    "localhost",
    "127.0.0.1",
]
# Application definition


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "authentication",
    "user_queries",
    "corsheaders",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.http.ConditionalGetMiddleware",
    # "django.middleware.security.StrictTransportSecurityMiddleware",
]

ROOT_URLCONF = "MnemosineV3_0.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "MnemosineV3_0.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
"""
DATABASES = {
    "default": {
        "ENGINE": "djongo",
        "NAME": "Mnemosine",
        "CLIENT": {
            "host": "mongodb://localhost:27017",
            'username': 'usuario1',
            'password': '123456',
        },
    }
}
"""

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Mexico_City"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Configuración de JWT
"""
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME":  timedelta(hours=4),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}
"""


CORS_ALLOW_ALL_ORIGINS = True


AUTH_USER_MODEL = "authentication.MyUser"
AUTHENTICATION_BACKENDS = [
    "authentication.backends.MongoAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
]

STATIC_PATH_DOCX = "/var/www/html/MnemosineReact/static/documents/app/reportes/"
BLANK_IMG = (
    "/var/www/html/MnemosineReact/static/documents/app/public/inventario/blank.png"
)
TEMPORARY_UPLOAD_DIRECTORY = (
    "/var/www/html/MnemosineReact/static/images/temporary_uploads/"
)
PHOTO_INVENTORY_PATH = (
    "/var/www/html/MnemosineReact/static/documents/app/public/inventario/fotos/"
)
THUMBNAILS_INVENTORY_PATH = "/var/www/html/MnemosineReact/static/documents/app/public/inventario/fotosThumbnails/"
PHOTO_RESEARCH_PATH = (
    "/var/www/html/MnemosineReact/static/documents/app/public/investigacion/fotos/"
)
THUMBNAILS_RESEARCH_PATH = "/var/www/html/MnemosineReact/static/documents/app/public/investigacion/fotosThumbnails/"
PHOTO_RESTORATION_PATH = (
    "/var/www/html/MnemosineReact/static/documents/app/public/restauracion/fotos/"
)
THUMBNAILS_RESTORATION_PATH = "/var/www/html/MnemosineReact/static/documents/app/public/restauracion/fotosThumbnails/"
DOCUMENT_INVENTORY_PATH = (
    "/var/www/html/MnemosineReact/static/documents/app/public/inventario/documentos/"
)
DOCUMENT_RESEARCH_PATH = (
    "/var/www/html/MnemosineReact/static/documents/app/public/investigacion/documentos/"
)
DOCUMENT_RESTORATION_PATH = (
    "/var/www/html/MnemosineReact/static/documents/app/public/restauracion/documentos/"
)

INSTITUTION_NAME = "Museo Franz Mayer"
POSITION_NAME_NEW_INVENTORY = "Directora de colecciones"

"""
Esto es para permitir CORS en el servidor de desarrollo de Django
quitar al finalizar el desarrollo
"""

AUDIT_MANAGER_TIME_ZONE = "America/Mexico_City"
CAMBIO_DE_TITULO = "Cambio de título"
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",    
    "http://192.168.1.70:3000",
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "OPTIONS",
    "PATCH",
]

CORS_ALLOW_HEADERS = [
    "Content-Type",
    "Authorization",
]

APPEND_SLASH = False
"""
SECURE_HSTS_SECONDS = 31536000  # 1 año
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
"""
